- name: NTP
  apt: pkg=ntp
- apt: pkg=vlan,iproute
- name: Useful stuff
  apt: pkg=tree,dstat,less,vim,bash-completion
- apt: pkg=screen
- copy: src=config/screenrc dest=/etc/screenrc
# Requires ansible 1.6
#- alternatives: name=editor path=/usr/bin/vim.basic
# Apt auto-update
- copy: src=config/apt-02periodic dest=/etc/apt/apt.conf.d/02periodic
- apt: pkg=unattended-upgrades
